version: '3.8'

services:
  oxypass-frontend:
    build: .
    container_name: oxypass-frontend
    ports:
      - "${VITE_PORT:-4000}:4000"
    environment:
      - NODE_ENV=production
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
      - VITE_PORT=${VITE_PORT:-4000}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - oxypass-network

networks:
  oxypass-network:
    driver: bridge
